POST https://cse341-project2-na2c.onrender.com/products
Authorization: Bearer COLE_O_TOKEN_AQUI
Content-Type: application/json

{
  "name": "Heavy Bag",
  "price": 399.99,
  "category": "Boxing",
  "brand": "Everlast",
  "stock": 5,
  "description": "Professional heavy bag",
  "rating": 4.9
}




### Get all products
GET http://localhost:8080/products



### Create product (VALID)
POST http://localhost:8080/products
Content-Type: application/json

{
  "name": "Boxing Gloves",
  "price": 199.90,
  "category": "Boxing",
  "brand": "Everlast",
  "stock": 10,
  "description": "Professional Gloves",
  "rating": 4.8
}



### Create invalid product (missing required fields)
POST http://localhost:8080/products
Content-Type: application/json

{
  "name": "",
  "price": -50
}



### Create product (VALID)
POST http://localhost:8080/products
Content-Type: application/json

{
  "name": "Muay Thai Shin Guards",
  "price": 149.99,
  "category": "Martial Arts",
  "brand": "Venum",
  "stock": 15,
  "description": "Professional shin guards for Muay Thai training",
  "rating": 4.7
}



### Get product by id
GET http://localhost:8080/products/697bef3c64d71f3886b42921



### Update product
PUT http://localhost:8080/products/69814e66b5b628514d8cf815
Content-Type: application/json

{
  "name": "Pro Boxing Gloves",
  "price": 249.90,
  "category": "Boxing",
  "brand": "Everlast",
  "stock": 8,
  "description": "Professional Gloves Updated",
  "rating": 4.9
}



### Delete product
DELETE http://localhost:8080/products/697bef3c64d71f3886b42921
